language: ruby
rvm:
- 2.1.0
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libmagickcore-dev libxml2-dev libxslt1-dev
- npm install -g bower
before_script:
- git clone --quiet --branch gh-pages "https://github.com/seisahachioji/takarock14.git"
  build/
- pushd build/
- git pull --quiet -u origin gh-pages
- git rm -rf .
- popd
- bower install
- bundle install
script:
- bundle exec middleman build
after_success:
- openssl aes-256-cbc -k $DEPLOY_KEY_PASSPHRASE -in deploy_key.enc -d -a -out deploy_key
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/github_seisahachioji_takarock14_deploy_key
- echo -e "\nHost github.com" >> ~/.ssh/config
- echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config
- echo -e "\tIdentityFile ~/.ssh/github_seisahachioji_takarock14_deploy_key" >> ~/.ssh/config
- pushd build/
- git add -A
- git commit -m Update
- git push --quiet "git@github.com:seisahachioji/takarock14.git" gh-pages
branches:
  only:
  - master
env:
  global:
  - secure: aSGaV0g8Tnf2D5TM/hGjOwizz3CAsrEhKV4QeXpiYTWV8onEl7wP+SLHveYUTUa9AeZHTWItt0xEFcg3GhAY49L+LoEIpEAREbYj+GR2ESzIjOLcZeCAJV1Vb4rHe1EMT/qJ8/fvb+/AWneXqN/F8EaYbmx12hqU3CmyZZbZ1uE=
  - GIT_COMMITTER_NAME="Travis CI (Shuma Yoshioka)"
  - GIT_AUTHOR_NAME="Travis CI (Shuma Yoshioka)"
  - GIT_COMMITTER_EMAIL="s64.stdio+gh-seisahachioji@gmail.com"
  - GIT_AUTHOR_EMAIL="s64.stdio+gh-seisahachioji@gmail.com"
  - JEKYLL_BUILD="gh-pages"
notifications:
  slack:
    secure: ofpMESN/JYq0rObu4rKVi0YUkZ51xuuUyU1g01mN5lqVY9pi1NBZM542jDrNbMfYyR4FB0X6eQvjLraS8jT+mudH/LQ8gh3QSqoRwDpbEvT4Y+/lrz5xR/acxUa8S6/2acIIQFTgr8wtIbatZ5w5OoM7H0mPdYqSHXiFkeop3Ts=
